### ISSUE TITLE
[Question] How are blog pages generated?

### ISSUE THREAD

**Issue by LeiYangGH** [mattosaurus/bitScry#8]
Hi,
 I cloned, read, while thinking I got to know the the basic structure, I'm more interested in the most complicated part, i.e. the blog pages themselves.

For example, in the pages, there are such parts:

- main contents
- Recent Posts
- Tag Cloud
- Reading List
- Categories
- Tags
- ... and more
But searching the coded couldn't show the keywords, so I thought these pages are just **static** pages you created manually, or generated by some other tools.

Can you confirm my thinking? and what tool did you use to generate the blog pages? Obviously they are hard to edit manually.

**Comment by mattosaurus** [comment]
Hi, the blog is a seperate [Wordpress](https://en-gb.wordpress.org/download/) site. It's actually pretty easy to create and edit content in Wordpress and as it's the biggest blogging platform it's very well supported with lots plugins available to add extra functionality.

**Comment by LeiYangGH** [comment]
Thanks!
